### ISSUE TITLE
Please add callnames attribute please

### ISSUE THREAD

**Issue by kanzusyauqi** [PeterC10/PESEditor#1]
Dear Peter. I very need callnames attribute in export and import csv files. Can you add it please...

**Comment by PeterC10** [comment]
Hello, this is included in the latest version (6.0.7.3), although it is only ID number. Hope that is of use.

Latest version can be downloaded at: https://mega.nz/file/CIZnjYbJ#z29qJHk8sF4jXsVaFfMIdMXP8qdCVnKfzw4pfcjh9lA

**Comment by kanzusyauqi** [comment]
Thank you very much. That is great.  But,  there is one thing that should
make it more perfect. FYI,  sound callnames is divided by 4 for some
players. Example, Cristiano Ronaldo callname. His callnames are:
9375 : "Cristiano Ronaldo"
12227: "And Cristiano Ronaldo"
12618: "Here is Cristiano Ronaldo"
13009: "Cristiano Ronaldo!!!! "

Could you add 3 more those callnames attribute please...  You can name them:

callname2
callname3
callname4

I hope you can do that

I very need that

Thank you


Pada tanggal Rab, 7 Okt 2020 07:01, Peter Clark <notifications@github.com>
menulis:

**Comment by kanzusyauqi** [comment]
Im so sorry for my previous email. I was fault. Your application is
perfect!!!  That callnames ID can integrate automatically with 3 other
callnames that i mentioned in previous email.

Im so sorry.

Good job Peter.

God bless you

Thank you very much

Pada tanggal Rab, 7 Okt 2020 08:01, Kanzu Syauqi <kanzusyauqi@gmail.com>
menulis:

**Comment by kanzusyauqi** [comment]
Hi Peter,
I want to ask you. Why do i cannot save csv file from this attached option
file?

**Comment by PeterC10** [comment]
I don't see any attachment?

**Comment by kanzusyauqi** [comment]
Can you see these attachments?

Pada tanggal Kam, 8 Okt 2020 03:45, Peter Clark <notifications@github.com>
menulis:

**Comment by kanzusyauqi** [comment]
Can you see these attachments?

---------- Forwarded message ---------
Dari: Kanzu Syauqi <kanzusyauqi@gmail.com>
Date: Rab, 7 Okt 2020 17:27
Subject: Re: [PeterC10/PESEditor] Please add callnames attribute please (#1)
To: PeterC10/PESEditor <
reply@reply.github.com>


Hi Peter,
I want to ask you. Why do i cannot save csv file from this attached option
file?

**Comment by PeterC10** [comment]
Nope, sorry. Maybe upload somewhere?

**Comment by kanzusyauqi** [comment]
https://www.mediafire.com/folder/a1d0ws36xnaap/ask peter

Those are my attachment.

**Comment by PeterC10** [comment]
That's a strange one, it can't get the position of the first edit player (<Edited 0> - ID 32768). As this player is not being used it should just default to GK.

I'll take a look at this over the weekend.

In the meantime just untick created players when doing the export (when you import a CSV it will only update the players included in the file anyway - and the created player IDs aren't currently being used)

Screenshot of the option to untick:

![image](https://user-images.githubusercontent.com/7999677/95513937-073a7680-09b3-11eb-92de-aff9c15fa9cd.png)

**Comment by kanzusyauqi** [comment]
Thank you very much

Pada tanggal Jum, 9 Okt 2020 04:10, Peter Clark <notifications@github.com>
menulis:

**Comment by kanzusyauqi** [comment]
Hi Peter,

I have problem in importing stats from csv. Here attachments:
http://www.mediafire.com/folder/ee4pllbx6i2ny/Import_Problem

i want to import stats from those csv into that option file.

How to solve this problem?

thank you

**Comment by PeterC10** [comment]
Haven't had a chance to check this out yet but will take a look when I do.

**Comment by PeterC10** [comment]
Issue should now be fixed in version 6.0.7.4 which can be downloaded here: https://mega.nz/file/qERixZ6Z#-fdfDwQVy_AT-PBt7Uaqkhi2mAb3rtZOnpFJtFYPssY
