### ISSUE TITLE
Report Bug on Hair Attribute

### ISSUE THREAD

**Issue by kanzusyauqi** [PeterC10/PESEditor#2]
Dear Peter,
I found bug in importing csv to option file in Hair Attribute.

When Hair type is Curly 1, if HAIR FRONT is not 3, csv file cannot be imported.
Hope you fix that. Thank you.

**Comment by PeterC10** [comment]
Thanks for reporting, will check that out. :)

**Comment by PeterC10** [comment]
Issue should now be fixed in version 6.0.7.4 which can be downloaded here: https://mega.nz/file/qERixZ6Z#-fdfDwQVy_AT-PBt7Uaqkhi2mAb3rtZOnpFJtFYPssY

**Comment by PeterC10** [comment]
Note: Unfortunately it was a bug with both importing and exporting the player, so you may need to export the players to CSV again.

Alternatively check that none of the hair columns have an empty value. If they do put "NA" in and that player should import fine.
